name: Deploy to Server

on:
  push:
    branches:
      - master # Deploy on branches

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/nfs/micro-service/quick-serve/api_gateway/ApiGateway

            echo "Pulling latest code..."
            git pull

            echo "Stoppin  g existing Docker container..."
            docker stop api_gateway_container || true
            docker rm api_gateway_container || true

            echo "Building Docker image..."
            docker build -t api_gateway_image .

            echo "Running Docker container..."
            docker run -d --name api_gateway_container -p 8079:8080 api_gateway_image
